# Generated by Django 2.1.7 on 2019-02-15 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('tags', models.CharField(max_length=250)),
                ('state', models.CharField(choices=[('created', 'created'), ('approved', 'approved'), ('rejected', 'rejected')], default='approved', max_length=15)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_web_app.Municipality')),
            ],
        ),
    ]
